version: 1.0
service_name: nepal-common

stages:
    -
        name: Master Push - Publish
        when:
            - push: ['abcd']
        image: node:13
        compute_size: small
        commands:
            - |
              set -ex
              
              printenv
              snap install hub --classic
              GITHUB_TOKEN=$ALPS_GH_TOKEN
              hub pr list

              
            - echo done
