version: 1.0
service_name: nepal-common

stages:
    -
        name: Master Push - Publish
        when:
            - push: ['abcd']
        image: node:13
        compute_size: small
        commands:
            - |
              set -ex
              
              printenv
              curl -fsSL https://github.com/github/hub/raw/master/script/get | bash
              GITHUB_TOKEN=$ALPS_GH_TOKEN
              bin/hub pr list

              
            - echo done
